# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python
name: Python application
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
    branches: [ "master" ]
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: SET UP PYTHON 3.13.3
      uses: actions/setup-python@v3
      with:
        python-version: "3.13.3"
    - name: INSTALL DEPENDENCIES
      run: |
        cd backend
        uv sync
    - name: GENERATE CODE COVERAGE
      run : |
        cd swippter
        coverage run manage.py test
    - name: UPLOAD COVERAGE REPORTS TO CODECOV WITH GITHUB ACTION
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}